### ISSUE TITLE
[AndroidAuto]

### ISSUE THREAD

**Issue by Tuxino88** [AndroidAudioMods/ViPERFX_RE#12]
would it be possible to enable androidauto support ?

**Comment by iscle** [comment]
Hi, it does process sound when using Android Auto, at least for me. Are you using wired or wireless?

**Comment by Tuxino88** [comment]
> Hi, it does process sound when using Android Auto, at least for me. Are you using wired or wireless?

Sorry I expressed myself badly.  I meant if it would be possible to display the viper4android application on the car screen.

**Comment by Martmists-GH** [comment]
As long as Android Auto support ViPER4Android, probably. We are not the developers of the app, we're only reverse-engineering the audio engine. I recommend asking @Pittvandewitt on [ViPER4Android's XDA thread](https://forum.xda-developers.com/t/app-all-root-solutions-6-0-viper4android-fx-2-7.3774651/).
