### ISSUE TITLE
AutoEQ Integration.

### ISSUE THREAD

**Issue by Naveed-SNR** [AndroidAudioMods/ViPERFX_RE#13]
Many EQ apps can load AutoEQ presets directly from the app. It would be great to have AutoEQ Integration for ViPER as it's much more convenient  to search and load presets from AutoEQ than looking for presets in the device storage.

**Comment by iscle** [comment]
Hi, this is already being discussed at https://github.com/AndroidAudioMods/ViPER4Android/issues/36

:)
