### ISSUE TITLE
Can't install the app

### ISSUE THREAD

**Issue by Naveed-SNR** [AndroidAudioMods/ViPERFX_RE#24]
Whenever I try installing the app, I get a message saying "App not installed as package conflicts with an existing package." I removed the older version and the old module before trying to install the latest one. I checked data/adb and sdcard/Android/data for any remnants from the previous install but I'm still not able to install the app. However, I had no issues flashing the module.

**Comment by Martmists-GH** [comment]
Did you mean to close this issue?

**Comment by iscle** [comment]
> Did you mean to close this issue?

The app conflicting with another package is not an issue we can fix, it's because he has another app with the same package name or different signature. So I assume he fixed it already ;)

**Comment by Naveed-SNR** [comment]
> > Did you mean to close this issue?
> 
> The app conflicting with another package is not an issue we can fix, it's because he has another app with the same package name or different signature. So I assume he fixed it already ;)

Sorry, I wanted to open the issue for a different repo (forked from this repo) but accidentally opened it here.

**Comment by Naveed-SNR** [comment]
> Did you mean to close this issue?
Yes
