### ISSUE TITLE
Make ViPERBass stereo

### ISSUE THREAD

**Issue by iscle** [AndroidAudioMods/ViPERFX_RE#7]
Right now ViPERBass adds up the two channels, processes the bass stuff, and adds the result to the two channels. 

This might cause crosstalk.

The best thing to do would be duplicate the logic and apply it to both channels separately.

**Comment by Martmists-GH** [comment]
I think it's best to first create a full 1:1 same behavior first and keep that on a separate branch, and then keep improvements on another branch.

**Comment by NBruderman** [comment]
Is there still a plan to implement this in the future?

**Comment by iscle** [comment]
> Is there still a plan to implement this in the future?

In fact, I just implemented it now. a947fd7f79dd1e252915a8c6f30255616e42b072

I have yet to test it, but it should be working. If you want and know how to, you can grab the libraries that github actions has generated and update them in your magisk zip.

**Comment by NBruderman** [comment]
> > Is there still a plan to implement this in the future?
> 
> In fact, I just implemented it now. a947fd7f79dd1e252915a8c6f30255616e42b072
> 
> I have yet to test it, but it should be working. If you want and know how to, you can grab the libraries that github actions has generated and update them in your magisk zip. 

Wow, the timing. And thank you very much!

**Comment by iscle** [comment]
It works :) You can download the module directly from here: https://github.com/AndroidAudioMods/ViPERFX_RE/actions/runs/6061819148 (version number is the same as before, i'll update in the following days).
